-- ─── Phase 8 billing + drift schema additions (CTRL-02..07) ───────────────
-- Generated by drizzle-kit, then manually augmented with CHECK constraints,
-- partial indexes, COMMENT ON COLUMN rows, and the TimescaleDB `usage_hourly`
-- continuous aggregate (Drizzle does not emit those natively).
--
-- Filename `20260428000000_phase8_billing_drift.sql` is FROZEN per D-28.
-- Idempotency: ALTER COLUMN uses ADD COLUMN IF NOT EXISTS so re-running the
-- migration on a partially-applied dev branch is safe.
--
-- References:
--   - .planning/phases/08-auth-billing/08-CONTEXT.md D-28 (frozen prefix)
--   - .planning/phases/08-auth-billing/08-RESEARCH.md §7 (full migration SQL)

-- ─── 1. organizations ALTERs ──────────────────────────────────────────────
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "subscription_status" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "quota_period_start" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
-- Tighten stripe_customer_id with UNIQUE (Phase 1 had it nullable, no UNIQUE).
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_stripe_customer_id_unique" UNIQUE("stripe_customer_id");--> statement-breakpoint

-- ─── 2. specs ALTER ───────────────────────────────────────────────────────
ALTER TABLE "specs" ADD COLUMN IF NOT EXISTS "parsed_ir_jsonb" jsonb;--> statement-breakpoint

-- ─── 3. deployments ALTER ─────────────────────────────────────────────────
ALTER TABLE "deployments" ADD COLUMN IF NOT EXISTS "auto_regenerate_on_drift" boolean DEFAULT false NOT NULL;--> statement-breakpoint

-- ─── 4. generations ALTERs (with CHECK constraint) ────────────────────────
ALTER TABLE "generations" ADD COLUMN IF NOT EXISTS "cumulative_cost_usd" numeric(10, 4) DEFAULT '0' NOT NULL;--> statement-breakpoint
ALTER TABLE "generations" ADD COLUMN IF NOT EXISTS "triggered_by" text DEFAULT 'user' NOT NULL;--> statement-breakpoint
ALTER TABLE "generations" ADD CONSTRAINT "generations_triggered_by_check" CHECK (triggered_by IN ('user', 'drift_auto', 'drift_manual'));--> statement-breakpoint

-- ─── 5. CREATE TABLE "subscription_events" ────────────────────────────────
CREATE TABLE "subscription_events" (
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" uuid,
	"event_type" text NOT NULL,
	"stripe_event_id" text NOT NULL UNIQUE,
	"payload" jsonb NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"processed_at" timestamp with time zone,
	"status" text DEFAULT 'received' NOT NULL CHECK (status IN ('received', 'processed', 'error')),
	"error_message" text
);
--> statement-breakpoint
ALTER TABLE "subscription_events" ADD CONSTRAINT "subscription_events_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "subscription_events_org_received_idx" ON "subscription_events" USING btree ("organization_id","received_at");--> statement-breakpoint

-- ─── 6. CREATE TABLE "drift_events" (with CHECK on status) ────────────────
CREATE TABLE "drift_events" (
	"id" text PRIMARY KEY NOT NULL,
	"deployment_id" uuid NOT NULL,
	"detected_at" timestamp with time zone DEFAULT now() NOT NULL,
	"diff_json" jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'reviewing', 'regenerating', 'resolved', 'dismissed')),
	"resolved_at" timestamp with time zone,
	"resolved_by_generation_id" uuid
);
--> statement-breakpoint
ALTER TABLE "drift_events" ADD CONSTRAINT "drift_events_deployment_id_deployments_id_fk" FOREIGN KEY ("deployment_id") REFERENCES "public"."deployments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "drift_events" ADD CONSTRAINT "drift_events_resolved_by_generation_id_generations_id_fk" FOREIGN KEY ("resolved_by_generation_id") REFERENCES "public"."generations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "drift_events_deployment_detected_idx" ON "drift_events" USING btree ("deployment_id","detected_at");--> statement-breakpoint

-- ─── 7. CREATE TABLE "drift_email_log" ────────────────────────────────────
CREATE TABLE "drift_email_log" (
	"tenant_id" uuid NOT NULL,
	"week_start" date NOT NULL,
	"sent_at" timestamp with time zone DEFAULT now() NOT NULL,
	"drift_event_count" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "drift_email_log_tenant_id_week_start_pk" PRIMARY KEY("tenant_id","week_start")
);
--> statement-breakpoint
ALTER TABLE "drift_email_log" ADD CONSTRAINT "drift_email_log_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

-- ─── 8. CREATE TABLE "usage_events_outbox" ────────────────────────────────
CREATE TABLE "usage_events_outbox" (
	"id" text PRIMARY KEY NOT NULL,
	"deployment_id" uuid NOT NULL,
	"event_type" text NOT NULL,
	"event_payload" jsonb NOT NULL,
	"idempotency_key" text NOT NULL UNIQUE,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"sent_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "usage_events_outbox" ADD CONSTRAINT "usage_events_outbox_deployment_id_deployments_id_fk" FOREIGN KEY ("deployment_id") REFERENCES "public"."deployments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

-- ─── 9. CREATE TABLE "reconciliation_log" ─────────────────────────────────
CREATE TABLE "reconciliation_log" (
	"id" text PRIMARY KEY NOT NULL,
	"reconciliation_date" date NOT NULL,
	"event_type" text NOT NULL,
	"tenant_id" uuid NOT NULL,
	"timescale_count" integer NOT NULL,
	"stripe_count" integer NOT NULL,
	"drift_pct" numeric(6, 3) NOT NULL,
	"alerted" boolean DEFAULT false NOT NULL,
	"run_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "reconciliation_log" ADD CONSTRAINT "reconciliation_log_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "reconciliation_log_unique" ON "reconciliation_log" USING btree ("reconciliation_date","event_type","tenant_id");--> statement-breakpoint

-- ─── 10. CREATE TABLE "mau_log" ───────────────────────────────────────────
CREATE TABLE "mau_log" (
	"sample_date" date PRIMARY KEY NOT NULL,
	"mau_count" integer NOT NULL,
	"alerted" boolean DEFAULT false NOT NULL,
	"sampled_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

-- ─── 11. Partial indexes (outbox poller + cost-cap accumulator hot paths) ─
CREATE INDEX IF NOT EXISTS "usage_events_outbox_pending_idx" ON "usage_events_outbox"("sent_at") WHERE "sent_at" IS NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "generations_status_idx" ON "generations"("status") WHERE "status" IN ('queued', 'running');--> statement-breakpoint

-- ─── 12. `usage_hourly` materialized view ─────────────────────────────────
-- DEVIATION (Wave 1): Neon ships TimescaleDB Apache edition (community), which
-- does NOT support continuous aggregates (`WITH (timescaledb.continuous)` and
-- `add_continuous_aggregate_policy` are TSL-licensed features). We fall back
-- to a regular PostgreSQL MATERIALIZED VIEW with manual REFRESH, driven by an
-- Inngest cron in Wave 2 (stripe-meters-emit-v1). API surface is unchanged —
-- downstream consumers only `SELECT FROM usage_hourly`. Documented in
-- 08-PHASE-DEVIATIONS.md (Plan 05 Task 2).
--
-- Read by the Stripe meters emitter (D-25) and the dashboard usage chart.
CREATE MATERIALIZED VIEW "usage_hourly" AS
SELECT
  time_bucket('1 hour', "time") AS bucket,
  "deployment_id",
  count(*) AS event_count,
  sum(coalesce("tokens_in", 0))::bigint AS tokens_in_total,
  sum(coalesce("tokens_out", 0))::bigint AS tokens_out_total,
  sum(case when "status" = 'error' then 1 else 0 end)::int AS error_count
FROM "usage_events"
GROUP BY bucket, "deployment_id"
WITH NO DATA;
--> statement-breakpoint
CREATE UNIQUE INDEX "usage_hourly_pk" ON "usage_hourly"(bucket, "deployment_id");--> statement-breakpoint

-- ─── 13. COMMENT ON COLUMN rows (operator-facing docs) ────────────────────
COMMENT ON COLUMN "organizations"."quota_period_start" IS 'Anchor timestamp for monthly quota windows; rolled forward by quota-period-rollover-v1 Inngest function.';
COMMENT ON COLUMN "generations"."cumulative_cost_usd" IS 'Running sum of LLM spend on this generation; cost-cap-enforcer-v1 cancels when > free $0.50 / pro $2.00.';
COMMENT ON COLUMN "generations"."triggered_by" IS 'user | drift_auto | drift_manual — distinguishes user-initiated vs drift-watcher regenerations.';
COMMENT ON COLUMN "deployments"."auto_regenerate_on_drift" IS 'When true, Drift Watcher creates a new generation automatically; otherwise emits drift_event with status=pending.';
