-- ─── Phase 11 playground execution schema ───────────────────────────────
-- Two tables powering the live playground (sandbox runs + saved-as-test
-- regression suite).
--
-- Generated by hand (mirrors Drizzle TS schema in
-- packages/contracts/src/db-schema.ts) following the same pattern as
-- 20260501010000_phase09_1_anon_flow.sql.
--
-- Filename `20260501020000_phase11_playground.sql` is FROZEN per Pitfall #18:
-- timestamp prefix strictly greater than the latest committed migration
-- `20260501010000_phase09_1_anon_flow.sql`, preserving lexicographic order.
--
-- Idempotency: CREATE TABLE IF NOT EXISTS + CREATE INDEX IF NOT EXISTS so
-- re-running on a partially-applied dev branch is safe.
--
-- References:
--   - packages/contracts/src/db-schema.ts (playground_runs / playground_tests)
--   - docs/decisions/001 (timestamp prefix native YYYYMMDDHHMMSS format)

-- ─── 1. playground_runs ─────────────────────────────────────────────────
-- One row per agent invocation in the playground UI. History rail reads
-- `WHERE generation_id = ? ORDER BY created_at DESC`.
--
-- `trace` is the full per-tool-call breakdown (ToolCall record + token
-- counts + latency + ok/error) as JSON array. UI renders this directly in
-- the right rail without parsing — same shape as the SSE events the engine
-- emits during invocation.
--
-- `org_id` scopes the row for tenant isolation; cascades when the
-- organization is deleted (no orphan playground history).
CREATE TABLE IF NOT EXISTS playground_runs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    generation_id   UUID NOT NULL REFERENCES generations(id) ON DELETE CASCADE,
    org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    prompt          TEXT NOT NULL,
    pinned_tool     TEXT,
    agent_reply     TEXT,
    trace           JSONB NOT NULL,
    total_in_tk     INTEGER NOT NULL DEFAULT 0,
    total_out_tk    INTEGER NOT NULL DEFAULT 0,
    total_lat_ms    INTEGER NOT NULL DEFAULT 0,
    status          TEXT NOT NULL,        -- 'ok' | 'failed'
    failure_reason  TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS playground_runs_gen_idx
    ON playground_runs (generation_id, created_at);
CREATE INDEX IF NOT EXISTS playground_runs_org_idx
    ON playground_runs (org_id, created_at);

-- ─── 2. playground_tests ────────────────────────────────────────────────
-- Saved-as-test snapshot of a successful playground run. The regression
-- suite reads these and re-runs each through the engine agent loop,
-- comparing the freshly-invoked tool sequence against `expected_tools`.
--
-- `expected_tools` captures the literal tool names the agent invoked when
-- the test was saved (not user-declared expectations). On suite run, a
-- failure means the new agent picked DIFFERENT tools — likely a Pass 2
-- description-quality regression.
--
-- `last_failure` is a structured object surfaced as a friendly message
-- in UI: { expected_tool: "list_objects", actual_tool: "search", hint:
-- "description overlaps" }.
CREATE TABLE IF NOT EXISTS playground_tests (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    generation_id   UUID NOT NULL REFERENCES generations(id) ON DELETE CASCADE,
    org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    source_run_id   UUID REFERENCES playground_runs(id) ON DELETE SET NULL,
    name            TEXT NOT NULL,
    prompt          TEXT NOT NULL,
    expected_tools  JSONB NOT NULL,       -- string[] of tool names
    last_status     TEXT,                 -- 'pass' | 'fail' | NULL (never run)
    last_run_at     TIMESTAMPTZ,
    last_failure    JSONB,                -- { expected_tool, actual_tool, hint }
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS playground_tests_gen_idx
    ON playground_tests (generation_id, created_at);
CREATE INDEX IF NOT EXISTS playground_tests_org_idx
    ON playground_tests (org_id, created_at);
