-- ─── Phase 1 init schema (FND-08) ─────────────────────────────────────────
-- Generated by drizzle-kit, then manually augmented with extension + hypertable DDL.
-- DO NOT auto-regenerate this file; subsequent schema changes go in NEW migration
-- files with timestamp prefix > 20260427000000.
--
-- Filename `20260427000000_init_schema.sql` is FROZEN per FND-08; the timestamp
-- prefix mitigates T-1-04 (migration filename collision) and Pitfall #18.

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- (Drizzle-generated CREATE TABLE statements follow — DO NOT edit below this comment manually;
--  edit packages/contracts/src/db-schema.ts and regenerate the migration as a NEW timestamped file.)

CREATE TABLE "deployments" (
	"id" uuid PRIMARY KEY NOT NULL,
	"generation_id" uuid NOT NULL,
	"cf_worker_name" text NOT NULL,
	"dispatch_namespace" text NOT NULL,
	"url" text NOT NULL,
	"auth_mode" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "deployments_cf_worker_name_unique" UNIQUE("cf_worker_name")
);
--> statement-breakpoint
CREATE TABLE "generations" (
	"id" uuid PRIMARY KEY NOT NULL,
	"project_id" uuid NOT NULL,
	"spec_id" uuid NOT NULL,
	"status" text NOT NULL,
	"current_stage" text,
	"options" jsonb NOT NULL,
	"ir" jsonb,
	"quality_report" jsonb,
	"quality_score" numeric(3, 2),
	"is_publishable" boolean,
	"llm_cost_usd" numeric(10, 6),
	"llm_cost_breakdown" jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" uuid PRIMARY KEY NOT NULL,
	"logto_org_id" text NOT NULL,
	"name" text NOT NULL,
	"plan_tier" text DEFAULT 'free' NOT NULL,
	"stripe_customer_id" text,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "organizations_logto_org_id_unique" UNIQUE("logto_org_id")
);
--> statement-breakpoint
CREATE TABLE "pending_callbacks" (
	"job_id" text NOT NULL,
	"event_id" text NOT NULL,
	"stage" text NOT NULL,
	"status" text NOT NULL,
	"attempted_count" integer DEFAULT 0 NOT NULL,
	"last_attempt_at" timestamp with time zone,
	"next_retry_at" timestamp with time zone,
	CONSTRAINT "pending_callbacks_job_id_event_id_pk" PRIMARY KEY("job_id","event_id")
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" uuid PRIMARY KEY NOT NULL,
	"org_id" uuid NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "specs" (
	"id" uuid PRIMARY KEY NOT NULL,
	"project_id" uuid NOT NULL,
	"content_hash" text NOT NULL,
	"format" text NOT NULL,
	"spec_url" text,
	"r2_key" text,
	"endpoint_count" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "tools" (
	"id" uuid PRIMARY KEY NOT NULL,
	"generation_id" uuid NOT NULL,
	"name" text NOT NULL,
	"tool_type" text NOT NULL,
	"description" jsonb NOT NULL,
	"input_schema" jsonb NOT NULL,
	"output_schema" jsonb NOT NULL,
	"annotations" jsonb NOT NULL,
	"response_config" jsonb NOT NULL,
	"embedding" vector(1536)
);
--> statement-breakpoint
CREATE TABLE "usage_events" (
	"time" timestamp with time zone NOT NULL,
	"deployment_id" uuid NOT NULL,
	"tool_name" text NOT NULL,
	"tokens_in" integer,
	"tokens_out" integer,
	"upstream_latency_ms" integer,
	"worker_cpu_ms" integer,
	"status" text NOT NULL,
	"client_type" text,
	"error_class" text
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"org_id" uuid NOT NULL,
	"email" text NOT NULL,
	"logto_user_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_logto_user_id_unique" UNIQUE("logto_user_id")
);
--> statement-breakpoint
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_generation_id_generations_id_fk" FOREIGN KEY ("generation_id") REFERENCES "public"."generations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generations" ADD CONSTRAINT "generations_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generations" ADD CONSTRAINT "generations_spec_id_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."specs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "specs" ADD CONSTRAINT "specs_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tools" ADD CONSTRAINT "tools_generation_id_generations_id_fk" FOREIGN KEY ("generation_id") REFERENCES "public"."generations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "specs_project_hash_idx" ON "specs" USING btree ("project_id","content_hash");--> statement-breakpoint
CREATE UNIQUE INDEX "tools_generation_name_idx" ON "tools" USING btree ("generation_id","name");--> statement-breakpoint
CREATE INDEX "usage_events_time_idx" ON "usage_events" USING btree ("time");--> statement-breakpoint
CREATE INDEX "usage_events_deployment_time_idx" ON "usage_events" USING btree ("deployment_id","time");
--> statement-breakpoint

-- ─── TimescaleDB hypertable for usage_events (architecture §7.2) ──────────
-- Convert usage_events to a hypertable partitioned by `time` column.
SELECT create_hypertable('usage_events', 'time', if_not_exists => TRUE);

-- Continuous aggregate for hourly rollups (used by quota enforcement; full continuous aggregate
-- view is added in a Phase-8 migration. This is the materialised view skeleton only.)
-- (Phase 8: add CREATE MATERIALIZED VIEW usage_hourly WITH (timescaledb.continuous) AS ...)
