-- ─── Phase 9.1 anonymous-hero-flow schema (D-09 / D-11 / OQ-2) ────────────
-- New tables + column extensions powering the anonymous generation pipeline.
-- Generated by hand (mirrors Drizzle TS schema in
-- packages/contracts/src/db-schema.ts) and manually augmented with
-- TimescaleDB hypertable, pgcrypto seed, and partial indexes — neither of
-- which Drizzle Kit emits natively.
--
-- Filename `20260501010000_phase09_1_anon_flow.sql` is FROZEN per Pitfall #18:
-- timestamp prefix is strictly greater than the latest committed migration
-- `20260501000000_phase10_initial_matview_refresh.sql` (10:00 same day),
-- preserving lexicographic order without colliding with concurrent Phase 10
-- work on main.
--
-- Idempotency: ALTER COLUMN uses ADD COLUMN IF NOT EXISTS so re-running the
-- migration on a partially-applied dev branch is safe. CREATE TABLE IF NOT
-- EXISTS keeps re-runs cheap. The `app_secrets` initial seed uses
-- `ON CONFLICT (key) DO NOTHING` so the first cron rotation after deploy is
-- not overwritten by a manual re-apply.
--
-- References:
--   - .planning/phases/09.1-anonymous-hero-flow/09.1-CONTEXT.md D-09 (schema)
--   - .planning/phases/09.1-anonymous-hero-flow/09.1-CONTEXT.md D-11 (salt store)
--   - .planning/phases/09.1-anonymous-hero-flow/09.1-RESEARCH.md §4 (TimescaleDB shape)
--   - .planning/phases/09.1-anonymous-hero-flow/09.1-RESEARCH.md §6 (OQ-2 cached_from FK)
--   - .planning/phases/09.1-anonymous-hero-flow/09.1-RESEARCH.md §"Pitfall #4"
--     (chunk_time_interval => 1 day vs default 7 days)

-- ─── 1. anonymous_generations ─────────────────────────────────────────────
-- One row per anonymous session. Anon ULID cookie maps to a generation_id.
-- `claimed_by_org_id` is set by POST /api/v1/claim_generation when a user
-- signs up and links the anon row to their org (D-04 claim flow).
CREATE TABLE IF NOT EXISTS "anonymous_generations" (
	"anon_session_id" text PRIMARY KEY NOT NULL,
	"generation_id" uuid NOT NULL,
	"ip_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"claimed_at" timestamp with time zone,
	"claimed_by_org_id" uuid
);
--> statement-breakpoint
ALTER TABLE "anonymous_generations" ADD CONSTRAINT "anonymous_generations_generation_id_generations_id_fk" FOREIGN KEY ("generation_id") REFERENCES "public"."generations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "anonymous_generations" ADD CONSTRAINT "anonymous_generations_claimed_by_org_id_organizations_id_fk" FOREIGN KEY ("claimed_by_org_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "anon_gen_session_idx" ON "anonymous_generations" USING btree ("anon_session_id");--> statement-breakpoint
-- Partial index powers the 7d unclaimed cleanup cron (D-06): index scan for
-- `WHERE claimed_at IS NULL AND created_at < NOW() - INTERVAL '7 days'`.
CREATE INDEX IF NOT EXISTS "anon_gen_unclaimed_idx" ON "anonymous_generations" USING btree ("created_at") WHERE "claimed_at" IS NULL;--> statement-breakpoint

-- ─── 2. anon_generation_log (TimescaleDB hypertable) ──────────────────────
-- High-insert-rate rate-limit log. BIGSERIAL (not UUID) because no global
-- uniqueness needed and it pairs cheaply with the hypertable partitioning
-- on `created_at`. Per RESEARCH §"Pitfall #4", hypertables enforce that
-- every UNIQUE index include the partitioning column — we add no UNIQUE
-- here, only a btree index on (ip_hash, created_at DESC).
CREATE TABLE IF NOT EXISTS "anon_generation_log" (
	"id" bigserial NOT NULL,
	"ip_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- Convert to TimescaleDB hypertable BEFORE creating indexes, so chunk
-- creation picks up the indexes automatically. `chunk_time_interval =>
-- INTERVAL '1 day'` per RESEARCH §"Pitfall #4": with founder's 30-day
-- retention this gives 30 chunks → drop_chunks atomically removes ~3.3%
-- of data per call (vs default 7-day chunks → 25% per call, coarser).
SELECT create_hypertable(
	'anon_generation_log',
	'created_at',
	chunk_time_interval => INTERVAL '1 day',
	if_not_exists => TRUE
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "anon_log_ip_time_idx" ON "anon_generation_log" USING btree ("ip_hash", "created_at" DESC);--> statement-breakpoint

-- ─── 3. app_secrets (daily-rotating salt store) ──────────────────────────
-- Single-table KV for app-level rotating secrets. Phase 9.1 uses keys
-- 'daily_salt_current' and 'daily_salt_previous' (per D-11). Future phases
-- may add more keys (e.g. webhook signing rotations).
CREATE TABLE IF NOT EXISTS "app_secrets" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"rotates_at" timestamp with time zone
);
--> statement-breakpoint
-- Initial seed: generate the first daily_salt_current via pgcrypto. The
-- pgcrypto extension is available in PG16+ contrib (Neon ships it). The
-- first cron rotation (anon-salt-rotate-v1, 00:00 UTC) promotes this to
-- daily_salt_previous and writes a fresh daily_salt_current.
-- ON CONFLICT DO NOTHING keeps re-applying the migration safe — never
-- overwrite a salt that has already started carrying real ip_hash data.
INSERT INTO "app_secrets" ("key", "value")
VALUES ('daily_salt_current', encode(gen_random_bytes(32), 'hex'))
ON CONFLICT ("key") DO NOTHING;
--> statement-breakpoint

-- ─── 4. deployments extension (anon ephemeral support) ───────────────────
-- `anon_session_id` links an ephemeral CF Workers for Platforms deployment
-- back to the anon row that created it (D-03). `expires_at` is set to
-- `created_at + 24 hours` for anon deploys; NULL for permanent (post-claim
-- or paid). The anon-tenant-expiry cron (Plan 09.1-10) deletes rows where
-- `expires_at < NOW()`.
ALTER TABLE "deployments" ADD COLUMN IF NOT EXISTS "anon_session_id" text;--> statement-breakpoint
ALTER TABLE "deployments" ADD COLUMN IF NOT EXISTS "expires_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_anon_session_id_anonymous_generations_anon_session_id_fk" FOREIGN KEY ("anon_session_id") REFERENCES "public"."anonymous_generations"("anon_session_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
-- Partial index powers the 24h ephemeral expiry cron: index scan for
-- `WHERE expires_at IS NOT NULL AND expires_at < NOW()`.
CREATE INDEX IF NOT EXISTS "deploy_expires_idx" ON "deployments" USING btree ("expires_at") WHERE "expires_at" IS NOT NULL;--> statement-breakpoint

-- ─── 5. generations.cached_from_generation_id (OQ-2 resolution) ──────────
-- Per RESEARCH §6 OQ-2: when User B's gen is served from User A's cache,
-- B gets a fresh `generations` row with this column pointing back to A's
-- row. Self-reference, ON DELETE SET NULL so deleting the original cache
-- source does not cascade-destroy downstream rows. Partial index
-- `gen_cached_from_idx` is for analytics ("how many gens were cache hits?")
-- and the cache-hit source lookup query in Plan 09.1-06.
ALTER TABLE "generations" ADD COLUMN IF NOT EXISTS "cached_from_generation_id" uuid;--> statement-breakpoint
ALTER TABLE "generations" ADD CONSTRAINT "generations_cached_from_generation_id_generations_id_fk" FOREIGN KEY ("cached_from_generation_id") REFERENCES "public"."generations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "gen_cached_from_idx" ON "generations" USING btree ("cached_from_generation_id") WHERE "cached_from_generation_id" IS NOT NULL;--> statement-breakpoint

-- ─── 6. COMMENT ON COLUMN rows (operator-facing docs) ────────────────────
COMMENT ON COLUMN "anonymous_generations"."ip_hash" IS 'sha256(daily_salt + raw_ip); daily-rotating salt limits backwards-traceability to 24h per D-11.';
COMMENT ON COLUMN "anonymous_generations"."claimed_at" IS 'Set by POST /api/v1/claim_generation (D-04). NULL = unclaimed (eligible for 7d cleanup cron).';
COMMENT ON COLUMN "anon_generation_log"."ip_hash" IS '30d retention via drop_chunks() — daily salt rotation makes pre-rotation hashes unrecoverable.';
COMMENT ON COLUMN "deployments"."expires_at" IS 'NULL for permanent deployments; created_at + 24h for anon ephemeral (D-03 / D-06).';
COMMENT ON COLUMN "generations"."cached_from_generation_id" IS 'Self-FK. Set when this row was served from L1 cache (D-05 / OQ-2). NULL for original generations.';
