-- ─── Phase 9 add public_badge to deployments (CTRL-08 / D-19) ─────────────
-- Generated by drizzle-kit then renamed to the FROZEN Phase-9 prefix per
-- Pitfall #18 (timestamp prefix MUST be strictly greater than 20260428000002 —
-- Phase 8). DO NOT auto-regenerate this file in place; subsequent schema
-- changes go in NEW migration files with timestamp prefix > 20260430000000.
--
-- Filename `20260430000000_phase9_badge_public.sql` is FROZEN per D-19 +
-- docs/decisions/001 (timestamp-prefix native YYYYMMDDHHMMSS format).
--
-- Idempotency: `ADD COLUMN IF NOT EXISTS` mirrors the Phase 8 pattern at
-- `20260428000002_phase8_billing_drift.sql:24` so re-running the migration
-- on a partially-applied dev branch is safe. Default `false` is privacy-safe
-- per Phase 7 dashboard UI (public quality badge is opt-in user choice).
--
-- References:
--   - .planning/phases/09-observability-polish/09-CONTEXT.md D-19
--   - .planning/phases/09-observability-polish/09-PATTERNS.md §"Phase 9 SQL"
--   - .planning/phases/09-observability-polish/09-RESEARCH.md §Pitfall #4 (journal sync)

ALTER TABLE "deployments" ADD COLUMN IF NOT EXISTS "public_badge" boolean DEFAULT false NOT NULL;
