-- ─── Phase 6 add idempotency_key to usage_events (RUN-06 / Open Question #6) ────
-- Generated by drizzle-kit, then manually augmented if needed.
-- DO NOT auto-regenerate this file; subsequent schema changes go in NEW migration
-- files with timestamp prefix > 20260428000001.
--
-- Filename `20260428000001_add_idempotency_key_to_usage_events.sql` is FROZEN; the
-- timestamp prefix mitigates Pitfall #18 per FND-08 / docs/decisions/001.
-- Closes contract-vs-DB drift: FROZEN UsageEvent Zod schema declared
-- idempotency_key since Phase 1 but the migrated DB did not store it.

ALTER TABLE "usage_events" ADD COLUMN "idempotency_key" text NOT NULL;--> statement-breakpoint
-- `time` is required in the unique index because `usage_events` is a TimescaleDB
-- hypertable partitioned on `time` — TimescaleDB enforces (TS103, hard DDL
-- constraint at indexing.c:ts_indexing_verify_columns) that every UNIQUE index
-- on a hypertable must include the partitioning column. Dedup semantics are
-- preserved because `idempotency_key` already encodes the minute-bucket
-- timestamp per Phase-1 D-11 shape `${deployment_id}_${minute_bucket_iso}_${tool_name}`,
-- so two events with the same (deployment_id, idempotency_key) share the same
-- `time` bucket. See docs/decisions/005-phase-6-schema-migrations.md.
CREATE UNIQUE INDEX "usage_events_dep_idem_unique" ON "usage_events" USING btree ("deployment_id","idempotency_key","time");
