-- ─── Phase 6 add local_port to deployments (RUN-01 / Open Question #1) ────
-- Generated by drizzle-kit, then manually augmented if needed.
-- DO NOT auto-regenerate this file; subsequent schema changes go in NEW migration
-- files with timestamp prefix > 20260428000000.
--
-- Filename `20260428000000_add_local_port_to_deployments.sql` is FROZEN; the
-- timestamp prefix mitigates Pitfall #18 per FND-08 / docs/decisions/001.

ALTER TABLE "deployments" ADD COLUMN "local_port" integer;
