# generated by datamodel-codegen:
#   filename:  ir.json

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, confloat, conint, constr


class FieldMcpgenIrRoot(BaseModel):
    pass


class Scheme(Enum):
    apiKey = "apiKey"
    oauth2 = "oauth2"
    http_basic = "http_basic"
    http_bearer = "http_bearer"
    aws_signature = "aws_signature"
    none = "none"


class RecommendedMode(Enum):
    passthrough = "passthrough"
    stored = "stored"
    oauth_flow = "oauth_flow"


class AuthRequirement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scheme: Scheme
    recommended_mode: RecommendedMode
    notes: Optional[str] = None


class Descriptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    purpose: constr(min_length=20)
    when_to_use: List[str] = Field(..., min_length=1)
    when_not_to_use: Optional[List[str]] = None
    how_to_use: Optional[str] = None
    limitations: List[str]
    parameter_overview: constr(min_length=50, max_length=400)
    description_hash: Optional[str] = None


class AuthoredTools(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    descriptions: Dict[str, Descriptions]


class SmartId(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: str
    types: List[str]
    collections: List[str]


class UniversalTool(Enum):
    search = "search"
    fetch = "fetch"
    list_collections = "list_collections"
    list_objects = "list_objects"
    upsert = "upsert"
    delete = "delete"


class Rule(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    universal_tool: UniversalTool
    target_endpoint: str
    params_mapping: Dict[str, str]


class Routing(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    smart_id: SmartId
    rules: List[Rule]


class Type(Enum):
    universal = "universal"
    action = "action"
    workflow = "workflow"
    specialized = "specialized"


class Description(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    purpose: constr(min_length=20)
    when_to_use: List[str] = Field(..., min_length=1)
    when_not_to_use: Optional[List[str]] = None
    how_to_use: Optional[str] = None
    limitations: List[str]
    parameter_overview: constr(min_length=50, max_length=400)
    description_hash: Optional[str] = None


class Annotations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    readOnlyHint: bool
    destructiveHint: bool
    idempotentHint: bool
    openWorldHint: Literal[True]


class Style(Enum):
    cursor = "cursor"
    offset = "offset"
    page_number = "page-number"
    none = "none"


class Pagination(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    style: Style
    default_limit: conint(le=9007199254740991, gt=0)
    max_limit: conint(le=9007199254740991, gt=0)


class FieldFiltering(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    always_include: List[str]
    opt_in: List[str]
    always_exclude: List[str]


class Truncation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    threshold_tokens: conint(le=9007199254740991, gt=0)
    guidance_template: str


class ResponseConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: Optional[Pagination] = None
    field_filtering: Optional[FieldFiltering] = None
    truncation: Truncation
    has_response_format_param: bool


class Tool(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    type: Type
    description: Description
    inputSchema: Dict[str, Any]
    outputSchema: Dict[str, Any]
    annotations: Annotations
    response_config: ResponseConfig
    source_endpoints: List[str]


class Step(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endpoint: str
    description: str


class PartialFailureStrategy(Enum):
    rollback = "rollback"
    continue_ = "continue"
    report = "report"


class Workflow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    steps: List[Step] = Field(..., max_length=5, min_length=2)
    partial_failure_strategy: PartialFailureStrategy


class CompleteServerSpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    server_name: str
    spec_hash: constr(pattern=r"^[a-f0-9]{64}$")
    routing: Routing
    tools: List[Tool]
    workflows: List[Workflow]


class CompositeCandidate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    steps: List[str] = Field(..., max_length=5, min_length=2)
    rationale: str


class SampleInvocation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: AnyUrl
    method: str
    params: Dict[str, Any]


class CoverageProof(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endpoint_id: str
    mapped_to_universal_tool: str
    sample_invocation: SampleInvocation


class DropReason(Enum):
    DEPRECATED = "DEPRECATED"
    INTERNAL = "INTERNAL"
    HEALTH_CHECK = "HEALTH_CHECK"
    WEBHOOK = "WEBHOOK"
    AUTH_FLOW = "AUTH_FLOW"
    REDUNDANT = "REDUNDANT"
    LOW_VALUE = "LOW_VALUE"
    USER_EXCLUDED = "USER_EXCLUDED"
    EXCEEDS_CAP = "EXCEEDS_CAP"
    METHOD_NOT_SUPPORTED = "METHOD_NOT_SUPPORTED"


class Reason(Enum):
    DEPRECATED = "DEPRECATED"
    INTERNAL = "INTERNAL"
    HEALTH_CHECK = "HEALTH_CHECK"
    WEBHOOK = "WEBHOOK"
    AUTH_FLOW = "AUTH_FLOW"
    REDUNDANT = "REDUNDANT"
    LOW_VALUE = "LOW_VALUE"
    USER_EXCLUDED = "USER_EXCLUDED"
    EXCEEDS_CAP = "EXCEEDS_CAP"
    METHOD_NOT_SUPPORTED = "METHOD_NOT_SUPPORTED"


class DroppedEndpoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: str
    path: str
    reason: Reason
    can_user_override: bool


class F1StaticReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    passed: bool
    ts_compile_errors: List[str]
    json_schema_errors: List[str]
    mcp_compliance_errors: List[str]
    secret_scan_findings: List[str]
    bundle_bytes: conint(ge=0, le=9007199254740991)


class Component1(Enum):
    purpose = "purpose"
    guidelines = "guidelines"
    limitations = "limitations"
    parameter_doc = "parameter_doc"
    examples = "examples"
    length_completeness = "length_completeness"


class Component(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    component: Component1
    score: confloat(ge=0.0, le=5.0)


class ToolScore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tool_name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    components: List[Component]
    average: confloat(ge=0.0, le=5.0)


class F2SmellReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tool_scores: List[ToolScore]
    overall_average: confloat(ge=0.0, le=5.0)
    passed: bool


class Component3(Enum):
    purpose = "purpose"
    guidelines = "guidelines"
    limitations = "limitations"
    parameter_doc = "parameter_doc"
    examples = "examples"
    length_completeness = "length_completeness"


class Component2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    component: Component3
    score: confloat(ge=0.0, le=5.0)


class F2ToolSmellScore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tool_name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    components: List[Component2]
    average: confloat(ge=0.0, le=5.0)


class Result(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task_id: str
    passed: bool
    judge_task_completion: confloat(ge=0.0, le=10.0)
    judge_grounding: confloat(ge=0.0, le=10.0)
    turns_used: conint(ge=0, le=9007199254740991)


class F3AgentEvalReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    results: List[Result]
    pass_rate: confloat(ge=0.0, le=1.0)
    passed: bool


class F3GoldenTaskResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task_id: str
    passed: bool
    judge_task_completion: confloat(ge=0.0, le=10.0)
    judge_grounding: confloat(ge=0.0, le=10.0)
    turns_used: conint(ge=0, le=9007199254740991)


class FieldFilteringConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    always_include: List[str]
    opt_in: List[str]
    always_exclude: List[str]


class Pagination1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    style: Style
    default_limit: conint(le=9007199254740991, gt=0)
    max_limit: conint(le=9007199254740991, gt=0)


class ResponseConfig1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: Optional[Pagination1] = None
    field_filtering: Optional[FieldFiltering] = None
    truncation: Truncation
    has_response_format_param: bool


class FinalTool(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    type: Type
    description: Description
    inputSchema: Dict[str, Any]
    outputSchema: Dict[str, Any]
    annotations: Annotations
    response_config: ResponseConfig1
    source_endpoints: List[str]


class PaginationConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    style: Style
    default_limit: conint(le=9007199254740991, gt=0)
    max_limit: conint(le=9007199254740991, gt=0)


class Category(Enum):
    search = "search"
    crud = "crud"
    action = "action"
    workflow = "workflow"
    specialized = "specialized"


class ToolPlan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    category: Category
    source_endpoints: List[str] = Field(..., min_length=1)
    rationale: str


class DroppedEndpoint1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: str
    path: str
    reason: Reason
    can_user_override: bool


class AuthRequirement1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scheme: Scheme
    recommended_mode: RecommendedMode
    notes: Optional[str] = None


class TargetComplexity(Enum):
    minimal = "minimal"
    standard = "standard"
    comprehensive = "comprehensive"


class Pass0Output(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tool_plans: List[ToolPlan]
    dropped_endpoints: List[DroppedEndpoint1]
    composite_candidates: List[CompositeCandidate]
    auth_requirements: Dict[str, List[AuthRequirement1]]
    target_complexity: TargetComplexity
    prompt_injection_warnings: List[str]


class Tool1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    type: Type
    source_endpoints: List[str]


class Rule1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    universal_tool: UniversalTool
    target_endpoint: str
    params_mapping: Dict[str, str]


class Routing1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    smart_id: SmartId
    rules: List[Rule1]


class Workflow1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    steps: List[Step] = Field(..., max_length=5, min_length=2)
    partial_failure_strategy: PartialFailureStrategy


class CoverageProofItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endpoint_id: str
    mapped_to_universal_tool: str
    sample_invocation: SampleInvocation


class Pass1Output(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tools: List[Tool1]
    routing: Routing1
    workflows: List[Workflow1]
    coverage_pct: confloat(ge=0.0, le=100.0)
    coverage_proof: List[CoverageProofItem]


class Pass2Output(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    descriptions: Dict[str, Descriptions]


class Pass3Output(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_schemas: Dict[str, Dict[str, Any]]


class Pass4Output(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    annotations: Dict[str, Annotations]
    titles: Dict[str, str]


class Pagination2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    style: Style
    default_limit: conint(le=9007199254740991, gt=0)
    max_limit: conint(le=9007199254740991, gt=0)


class ResponseConfig2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: Optional[Pagination2] = None
    field_filtering: Optional[FieldFiltering] = None
    truncation: Truncation
    has_response_format_param: bool


class Tool2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    type: Type
    description: Description
    inputSchema: Dict[str, Any]
    outputSchema: Dict[str, Any]
    annotations: Annotations
    response_config: ResponseConfig2
    source_endpoints: List[str]


class Pass5Output(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tools: List[Tool2]


class QualityBadge(Enum):
    premium = "premium"
    verified = "verified"
    standard = "standard"
    needs_review = "needs_review"


class F1Static(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    passed: bool
    ts_compile_errors: List[str]
    json_schema_errors: List[str]
    mcp_compliance_errors: List[str]
    secret_scan_findings: List[str]
    bundle_bytes: conint(ge=0, le=9007199254740991)


class Component5(Enum):
    purpose = "purpose"
    guidelines = "guidelines"
    limitations = "limitations"
    parameter_doc = "parameter_doc"
    examples = "examples"
    length_completeness = "length_completeness"


class Component4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    component: Component5
    score: confloat(ge=0.0, le=5.0)


class ToolScore1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tool_name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    components: List[Component4]
    average: confloat(ge=0.0, le=5.0)


class F2Smell(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tool_scores: List[ToolScore1]
    overall_average: confloat(ge=0.0, le=5.0)
    passed: bool


class F3AgentEval(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    results: List[Result]
    pass_rate: confloat(ge=0.0, le=1.0)
    passed: bool


class QualityReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spec_hash: constr(pattern=r"^[a-f0-9]{64}$")
    f1_static: F1Static
    f2_smell: F2Smell
    f3_agent_eval: Optional[F3AgentEval] = None
    overall_score: confloat(ge=0.0, le=5.0)
    quality_badge: QualityBadge


class Method(Enum):
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    PATCH = "PATCH"
    DELETE = "DELETE"
    HEAD = "HEAD"
    OPTIONS = "OPTIONS"


class RawEndpoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Method
    path: str
    operation_id: Optional[str] = None
    summary: Optional[str] = None
    description: Optional[str] = None
    parameters: List[Dict[str, Any]]
    request_body: Optional[Dict[str, Any]] = None
    responses: Dict[str, Any]
    tags: List[str]
    deprecated: bool


class SpecFormat(Enum):
    openapi_3_0 = "openapi-3.0"
    openapi_3_1 = "openapi-3.1"
    graphql = "graphql"
    postman = "postman"


class Endpoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Method
    path: str
    operation_id: Optional[str] = None
    summary: Optional[str] = None
    description: Optional[str] = None
    parameters: List[Dict[str, Any]]
    request_body: Optional[Dict[str, Any]] = None
    responses: Dict[str, Any]
    tags: List[str]
    deprecated: bool


class Type4(Enum):
    apiKey = "apiKey"
    http = "http"
    oauth2 = "oauth2"
    openIdConnect = "openIdConnect"
    mutualTLS = "mutualTLS"


class In(Enum):
    header = "header"
    query = "query"
    cookie = "cookie"


class SecuritySchemes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type4
    scheme: Optional[str] = None
    in_: Optional[In] = Field(..., alias="in")
    name: Optional[str] = None
    flows: Optional[Dict[str, Any]] = None


class RawIR(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spec_format: SpecFormat
    spec_hash: constr(pattern=r"^[a-f0-9]{64}$")
    endpoints: List[Endpoint]
    schemas: Dict[str, Any]
    security_schemes: Dict[str, SecuritySchemes]
    dependency_graph: Dict[str, List[str]]


class Pagination3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    style: Style
    default_limit: conint(le=9007199254740991, gt=0)
    max_limit: conint(le=9007199254740991, gt=0)


class ResponseConfig3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: Optional[Pagination3] = None
    field_filtering: Optional[FieldFiltering] = None
    truncation: Truncation
    has_response_format_param: bool


class Rule2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    universal_tool: UniversalTool
    target_endpoint: str
    params_mapping: Dict[str, str]


class RoutingConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    smart_id: SmartId
    rules: List[Rule2]


class RoutingRule(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    universal_tool: UniversalTool
    target_endpoint: str
    params_mapping: Dict[str, str]


class Component6(Enum):
    purpose = "purpose"
    guidelines = "guidelines"
    limitations = "limitations"
    parameter_doc = "parameter_doc"
    examples = "examples"
    length_completeness = "length_completeness"


class RubricComponentScore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    component: Component6
    score: confloat(ge=0.0, le=5.0)


class SecurityScheme(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type4
    scheme: Optional[str] = None
    in_: Optional[In] = Field(..., alias="in")
    name: Optional[str] = None
    flows: Optional[Dict[str, Any]] = None


class SmartIdSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: str
    types: List[str]
    collections: List[str]


class ToolAnnotations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    readOnlyHint: bool
    destructiveHint: bool
    idempotentHint: bool
    openWorldHint: Literal[True]


class ToolDescription(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    purpose: constr(min_length=20)
    when_to_use: List[str] = Field(..., min_length=1)
    when_not_to_use: Optional[List[str]] = None
    how_to_use: Optional[str] = None
    limitations: List[str]
    parameter_overview: constr(min_length=50, max_length=400)
    description_hash: Optional[str] = None


class ToolPlan1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    category: Category
    source_endpoints: List[str] = Field(..., min_length=1)
    rationale: str


class Type6(Enum):
    universal = "universal"
    action = "action"
    workflow = "workflow"
    specialized = "specialized"


class Tool3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    type: Type6
    source_endpoints: List[str]


class Rule3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    universal_tool: UniversalTool
    target_endpoint: str
    params_mapping: Dict[str, str]


class Routing2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    smart_id: SmartId
    rules: List[Rule3]


class Workflow2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    steps: List[Step] = Field(..., max_length=5, min_length=2)
    partial_failure_strategy: PartialFailureStrategy


class CoverageProofItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endpoint_id: str
    mapped_to_universal_tool: str
    sample_invocation: SampleInvocation


class ToolTaxonomy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tools: List[Tool3]
    routing: Routing2
    workflows: List[Workflow2]
    coverage_pct: confloat(ge=0.0, le=100.0)
    coverage_proof: List[CoverageProofItem1]


class ToolTaxonomyEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    type: Type6
    source_endpoints: List[str]


class TruncationConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    threshold_tokens: conint(le=9007199254740991, gt=0)
    guidance_template: str


class WorkflowDef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    steps: List[Step] = Field(..., max_length=5, min_length=2)
    partial_failure_strategy: PartialFailureStrategy


class WorkflowStep(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endpoint: str
    description: str
