// apps/web/src/components/screens/admin/users/users.snapshot.spec.ts
//
// Phase 3 / C2-users — Admin Users visual snapshot.
//
// Per the Phase 3 brief ("snapshot at 1280 width is enough for admin (no
// mobile responsiveness audit per Phase 5 brief)") and SHARED-BRIEF.md
// "Visual snapshot test pattern" — capture a single 1280-wide screenshot
// of `/admin/users` and compare against the canon baseline.
//
// Boot mode: web is already running on :3000 in the integration env. The
// `/admin/*` tree is gated by `ui_admin_panel_perm` (default OFF) which
// 404s the route in production. To exercise this snapshot the test
// environment must flip the flag ON (Phase 0 dev override) — when OFF the
// snapshot will fail-fast with a 404 page, which is the correct
// production behavior.
//
// Note: the canon visual baseline for this screen (`admin-users-1280.png`)
// is generated by the canon dev harness; the first run of this test
// produces the snapshot via Playwright's standard --update-snapshots flag.

import { expect, test } from '@playwright/test';

test('admin-users @ 1280 matches canon baseline', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto('http://localhost:3000/admin/users');
  await page.waitForLoadState('networkidle');

  const screenshot = await page.screenshot({ fullPage: true });
  expect(screenshot).toMatchSnapshot({
    name: 'admin-users-1280.png',
    maxDiffPixelRatio: 0.005,
  });
});
