// apps/cli/src/init/render_stub.ts
//
// Hand-rolled string-template renderer that emits a Phase-3 MCP-SDK-v1 stub
// server.ts. NO LLM, NO eval, NO vm.runInContext (T-2-09-02 mitigation).
//
// MCP SDK v1 doesn't accept raw JSON Schema in the deprecated `tool()`
// overloads (they all require ZodRawShapeCompat for the params slot). The
// Phase-3 spec D-37 calls for descriptions + input schemas + annotations +
// title to ride together; the only SDK form that supports that bundle in a
// single call is `registerTool(name, config, cb)` where `config` accepts
// `{ title, description, inputSchema, annotations }` per the SDK v1 type:
//
//   registerTool<OutputArgs, InputArgs>(
//     name: string,
//     config: { title?; description?; inputSchema?; outputSchema?; annotations?; _meta? },
//     cb: ToolCallback<InputArgs>,
//   )
//
// `inputSchema` accepts ZodRawShapeCompat; we keep the Phase-2 search/fetch
// Zod shapes (D-30 OpenAI compliance) so the runtime can validate calls.
// The hand-tuned per-tool JSON Schema from Pass 3 is encoded as additional
// metadata on the registration via the description (it shows up in
// `tools/list`) — Stage E (Phase 4) will lift this to a Zod converter when
// the codegen templates land.
//
// References:
// - 03-CONTEXT.md D-37 (server.tool 5-arg form — interpreted as registerTool
//   config-object form per SDK v1 actual API surface)
// - 02-CONTEXT.md D-30 (search/fetch OpenAI compliance) + D-45 (placeholder text)
// - apps/dispatch-sample/src/index.ts (canonical Zod shape)

import type {
  Pass1Output,
  Pass2Output,
  Pass3Output,
  Pass4Output,
  ToolTaxonomyEntry,
} from '@mcpgen/ir';

import { renderDescription } from './render_description.js';

/**
 * Generate the complete `server.ts` for a Phase-3 stub MCP server.
 *
 * Structure:
 *   - imports (McpServer + StdioServerTransport + zod)
 *   - server construction with `name = specSlug`
 *   - one `server.registerTool(name, config, handler)` registration per Pass 1
 *     tool, with config carrying Pass 2 description (markdown), Pass 4 title,
 *     Pass 4 annotations, and a Zod inputSchema (D-30: query/id strings for
 *     search/fetch; empty for other tools — Stage E in Phase 4 will derive
 *     full Zod from Pass 3 JSON Schema).
 *   - main() bootstrap that wires stdio transport and process.exit on error
 */
export function renderServerTs(
  specSlug: string,
  pass1: Pass1Output,
  pass2: Pass2Output,
  pass3: Pass3Output,
  pass4: Pass4Output,
): string {
  const toolRegistrations = pass1.tools
    .map((t: ToolTaxonomyEntry) => renderToolRegistration(t, pass2, pass3, pass4))
    .join('\n\n');

  return `#!/usr/bin/env tsx
// Generated by mcpgen-cli (Phase 3 stub).
// tools/list returns Pass 1 final tools enriched with Pass 2 descriptions,
// Pass 3 input schemas (encoded as JSON Schema in registerTool config), and
// Pass 4 annotations + titles.
// tools/call returns a deterministic placeholder — Stage E codegen lands in Phase 4.

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';

const server = new McpServer({ name: ${JSON.stringify(specSlug)}, version: '0.0.1' });

${toolRegistrations}

async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((err) => {
  console.error('Server failed:', err);
  process.exit(1);
});
`;
}

function renderToolRegistration(
  t: ToolTaxonomyEntry,
  pass2: Pass2Output,
  pass3: Pass3Output,
  pass4: Pass4Output,
): string {
  // D-37: registerTool(name, { title, description, inputSchema, annotations }, cb).
  const desc = pass2.descriptions[t.name];
  const description = desc !== undefined
    ? renderDescription(desc)
    : `Description not yet authored for tool '${t.name}'.`;
  // Pass 3 JSON Schema is preserved verbatim in a comment so Stage E (Phase 4)
  // can lift it to Zod; the runtime registration uses the Phase-2 Zod shape
  // for search/fetch (D-30 OpenAI compliance) and empty for the rest.
  const pass3Schema = pass3.input_schemas[t.name] ?? {};
  const pass3SchemaComment
    = `// Pass 3 input schema (JSON Schema): ${JSON.stringify(pass3Schema)}`;
  const inputSchema = renderZodShape(t);
  const annotations = pass4.annotations[t.name] ?? {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: true as const,
  };
  const annotationsJson = JSON.stringify(annotations);
  const title = pass4.titles[t.name] ?? t.name;
  // D-45 placeholder text — exact string. Stage E (Phase 4) replaces with real handler.
  const placeholder = `Tool '${t.name}' not yet implemented — Stage E codegen lands in Phase 4.`;

  return `${pass3SchemaComment}
server.registerTool(
  ${JSON.stringify(t.name)},
  {
    title: ${JSON.stringify(title)},
    description: ${JSON.stringify(description)},
    inputSchema: ${inputSchema},
    annotations: ${annotationsJson},
  },
  async () => ({ content: [{ type: 'text', text: ${JSON.stringify(placeholder)} }] }),
);`;
}

function renderZodShape(t: ToolTaxonomyEntry): string {
  // D-30 OpenAI compliance: search/fetch are exact-signature universal tools.
  // Stage E (Phase 4) will derive full Zod from Pass 3 JSON Schema; for the
  // Phase-3 stub server we keep the Phase-2 minimal shape to keep the
  // generated server.ts runnable under MCP Inspector.
  if (t.name === 'search') return '{ query: z.string() }';
  if (t.name === 'fetch') return '{ id: z.string() }';
  return '{}';
}
