// apps/cli/src/init/render_stub.ts
//
// Hand-rolled string-template renderer that emits a Phase-2 MCP-SDK-v1 stub
// server.ts. NO LLM, NO eval, NO vm.runInContext (T-2-09-02 mitigation).
//
// MCP SDK signature is the v1 form `server.tool(name, description,
// schemaShape, handler)` — mirrors `apps/dispatch-sample/src/index.ts` shape
// EXACTLY. Phase 4 Stage E will emit the same shape with real handler bodies.
//
// `tools/list` returns the real Pass 1 final tools; `tools/call` returns
// the deterministic D-45 placeholder.
//
// References:
// - 02-CONTEXT.md D-30 (OpenAI compliance) + D-45 (placeholder text exact)
// - 02-RESEARCH.md §"Pattern 8: MCP TS SDK v1 Stub Server Generator"
// - apps/dispatch-sample/src/index.ts (canonical shape)

import type { Pass1Output, ToolTaxonomyEntry } from '@mcpgen/ir';

/**
 * Generate the complete `server.ts` for a Phase-2 stub MCP server.
 *
 * Structure:
 *   - imports (McpServer + StdioServerTransport + zod)
 *   - server construction with `name = specSlug`
 *   - one `server.tool(...)` registration per Pass 1 tool
 *   - main() bootstrap that wires stdio transport and process.exit on error
 */
export function renderServerTs(
  specSlug: string,
  pass1: Pass1Output,
): string {
  const toolRegistrations = pass1.tools.map(renderToolRegistration).join('\n\n');

  return `#!/usr/bin/env tsx
// Generated by mcpgen-cli (Phase 2 stub).
// tools/list returns the real Pass 1 final tools.
// tools/call returns a deterministic placeholder — Stage E codegen lands in Phase 4.

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';

const server = new McpServer({ name: ${JSON.stringify(specSlug)}, version: '0.0.1' });

${toolRegistrations}

async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((err) => {
  console.error('Server failed:', err);
  process.exit(1);
});
`;
}

function renderToolRegistration(t: ToolTaxonomyEntry): string {
  // v1 SDK signature: server.tool(name, description, schemaShape, handler).
  const schemaShape = renderZodShape(t);
  const placeholder = `Tool '${t.name}' not yet implemented — Stage E codegen lands in Phase 4.`;
  const description = renderDescription(t);

  return `server.tool(
  ${JSON.stringify(t.name)},
  ${JSON.stringify(description)},
  ${schemaShape},
  async () => ({ content: [{ type: 'text', text: ${JSON.stringify(placeholder)} }] }),
);`;
}

function renderZodShape(t: ToolTaxonomyEntry): string {
  // D-30 OpenAI compliance: search/fetch are exact-signature universal tools.
  // Pass 3 (Phase 3) replaces the empty shape for everything else.
  if (t.name === 'search') return '{ query: z.string() }';
  if (t.name === 'fetch') return '{ id: z.string() }';
  return '{}';
}

function renderDescription(t: ToolTaxonomyEntry): string {
  // Phase-2 placeholder — Pass 2 (Phase 3) replaces with the 5-of-6 paper
  // rubric components. Surface enough metadata to keep Inspector / Claude
  // Desktop happy: tool type + source endpoint count.
  const typeLabel = t.type === 'universal'
    ? 'Universal'
    : `${t.type[0]?.toUpperCase() ?? ''}${t.type.slice(1)}`;
  const ep = t.source_endpoints.length;
  const plural = ep === 1 ? 'endpoint' : 'endpoints';
  return `${typeLabel} tool '${t.name}' wraps ${ep} upstream ${plural}. Pass 2 description authoring lands in Phase 3.`;
}
