"""Packager — generates Dockerfile, README, .env.example, and tar.gz archive."""

import io
import tarfile
from datetime import datetime, timezone

from backend.agents.models import GeneratedServer


def generate_dockerfile(server: GeneratedServer) -> str:
    """Generate a Dockerfile for the MCP server."""
    return """FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s \\
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/mcp')" || exit 1

CMD ["python", "server.py"]
"""


def generate_readme(server: GeneratedServer, server_name: str) -> str:
    """Generate a README.md for the MCP server."""
    env_vars_section = "\n".join(f"| `{var}` | Required | |" for var in server.env_vars)

    return f"""# {server_name}

Auto-generated MCP server by [mcpgen](https://github.com/Isk4R1oT/mcpgen).

## Quick Start

### Docker (recommended)

```bash
docker build -t {server_name} .
docker run -p 8000:8000 --env-file .env {server_name}
```

### Local

```bash
pip install -r requirements.txt
cp .env.example .env
# Edit .env with your credentials
{server.startup_command}
```

## Environment Variables

| Variable | Required | Description |
|----------|----------|-------------|
{env_vars_section}

## Connect MCP Client

**Claude Desktop** (HTTP):
Settings -> Connectors -> Add -> `http://localhost:8000/mcp`

**Claude Desktop** (Docker stdio):
```json
{{
  "mcpServers": {{
    "{server_name}": {{
      "command": "docker",
      "args": ["run", "-i", "--rm", "--env-file", ".env", "{server_name}"]
    }}
  }}
}}
```

## Files

{chr(10).join(f"- `{f.filename}` — {f.description}" for f in server.files)}
- `requirements.txt` — Python dependencies
- `Dockerfile` — Container build file
- `.env.example` — Environment variable template

---
Generated by mcpgen on {datetime.now(timezone.utc).strftime("%Y-%m-%d")}
"""


def generate_env_example(server: GeneratedServer) -> str:
    """Generate .env.example with all required env vars."""
    lines = []
    for var in server.env_vars:
        lines.append(f"{var}=")
    return "\n".join(lines) + "\n"


def create_source_archive(server: GeneratedServer, server_name: str) -> bytes:
    """Create a .tar.gz archive with all server files + Dockerfile + README."""
    buf = io.BytesIO()

    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        prefix = server_name

        # Add generated server files
        for f in server.files:
            _add_string_to_tar(tar, f"{prefix}/{f.filename}", f.content)

        # Add requirements.txt
        requirements_content = "\n".join(server.requirements) + "\n"
        _add_string_to_tar(tar, f"{prefix}/requirements.txt", requirements_content)

        # Add Dockerfile
        dockerfile_content = generate_dockerfile(server)
        _add_string_to_tar(tar, f"{prefix}/Dockerfile", dockerfile_content)

        # Add README.md
        readme_content = generate_readme(server, server_name)
        _add_string_to_tar(tar, f"{prefix}/README.md", readme_content)

        # Add .env.example
        env_content = generate_env_example(server)
        _add_string_to_tar(tar, f"{prefix}/.env.example", env_content)

    return buf.getvalue()


def _add_string_to_tar(tar: tarfile.TarFile, name: str, content: str) -> None:
    """Add a string as a file to a tar archive."""
    data = content.encode("utf-8")
    info = tarfile.TarInfo(name=name)
    info.size = len(data)
    info.mtime = int(datetime.now(timezone.utc).timestamp())
    tar.addfile(info, io.BytesIO(data))
