// apps/api/src/inngest/functions/flag-debt-audit.ts
//
// Feature management: weekly stale-flag scanner. Per
// docs/mcpgen-feature-flags-contract.md §5.4.
//
// Reads packages/feature-flags/_manifest/flags.yaml. For every flag with
// category in {rollout, exp} whose `expected_removal_at` is in the past,
// opens a GitHub issue with label `flag-debt`. Idempotent — searches for an
// existing open issue with the same title before creating.
//
// Schedule: every Monday 06:00 UTC (= 09:00 Europe/Moscow per contract).
// Stable function ID: INNGEST_FUNCTION_IDS.FLAG_DEBT_AUDIT.
//
// Wiring: this function is REGISTERED but should be ENABLED in the Inngest
// dashboard manually after first review. Locally it can be invoked via the
// Inngest dev server's "Invoke" button.
//
// Env vars:
//   GITHUB_TOKEN     — fine-grained PAT with issues:write on the mcpgen repo
//   GITHUB_REPO      — "owner/repo" (default: "Isk4R1oT/mcpgen")
//   FLAG_MANIFEST_URL — optional; defaults to in-repo path resolution.

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { INNGEST_FUNCTION_IDS } from '@mcpgen/contracts/inngest-functions';
import { inngest } from '../client.js';

interface FlagManifestEntry {
  key: string;
  category: 'kill' | 'rollout' | 'exp' | 'perm' | 'ops';
  owner: string;
  created_at: string;
  expected_removal_at?: string;
  notes?: string;
}

interface FlagManifest {
  flags: FlagManifestEntry[];
}

interface OverdueFlag {
  key: string;
  category: 'rollout' | 'exp';
  owner: string;
  expected_removal_at: string;
  daysOverdue: number;
}

const MANIFEST_PATH_CANDIDATES = [
  // Local dev — resolved relative to apps/api in the monorepo
  join(process.cwd(), '..', '..', 'packages', 'feature-flags', '_manifest', 'flags.yaml'),
  // Repo-root invocation
  join(process.cwd(), 'packages', 'feature-flags', '_manifest', 'flags.yaml'),
];

export function loadManifest(): FlagManifest {
  for (const path of MANIFEST_PATH_CANDIDATES) {
    if (existsSync(path)) {
      const raw = readFileSync(path, 'utf8');
      return parseYaml(raw) as FlagManifest;
    }
  }
  throw new Error(
    `flags manifest not found in any candidate path: ${MANIFEST_PATH_CANDIDATES.join(', ')}`,
  );
}

export function findOverdue(manifest: FlagManifest, today: Date): OverdueFlag[] {
  const todayStr = today.toISOString().slice(0, 10);
  const out: OverdueFlag[] = [];
  for (const entry of manifest.flags) {
    if (entry.category !== 'rollout' && entry.category !== 'exp') continue;
    if (entry.expected_removal_at === undefined) continue;
    if (entry.expected_removal_at >= todayStr) continue;
    const expected = new Date(entry.expected_removal_at + 'T00:00:00Z');
    const daysOverdue = Math.floor(
      (today.getTime() - expected.getTime()) / (1000 * 60 * 60 * 24),
    );
    out.push({
      key: entry.key,
      category: entry.category,
      owner: entry.owner,
      expected_removal_at: entry.expected_removal_at,
      daysOverdue,
    });
  }
  return out;
}

interface GhIssue {
  number: number;
  title: string;
  state: 'open' | 'closed';
}

async function findExistingIssue(
  repo: string,
  token: string,
  title: string,
): Promise<GhIssue | undefined> {
  const q = encodeURIComponent(`repo:${repo} is:issue is:open label:flag-debt in:title "${title}"`);
  const res = await fetch(`https://api.github.com/search/issues?q=${q}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' },
  });
  if (!res.ok) return undefined;
  const data = (await res.json()) as { items?: GhIssue[] };
  return data.items?.find((i) => i.title === title && i.state === 'open');
}

async function createIssue(
  repo: string,
  token: string,
  flag: OverdueFlag,
): Promise<{ number: number }> {
  const title = `flag-debt: ${flag.key} overdue by ${flag.daysOverdue} day(s)`;
  const body = [
    `**Flag overdue:** \`${flag.key}\``,
    `**Expected removal:** ${flag.expected_removal_at} (${flag.daysOverdue} days overdue)`,
    `**Owner:** ${flag.owner}`,
    `**Category:** ${flag.category}`,
    '',
    '### Checklist',
    '- [ ] Rollout reached 100% (or experiment chose a winner)?',
    '- [ ] Soak period (7 days) passed?',
    '- [ ] Old code path removed and `if (flag)` simplified?',
    '- [ ] Postmortem added to `_archive/`?',
    '',
    '_Auto-generated by `flag-debt-audit-v1` Inngest cron — see `docs/mcpgen-feature-flags-contract.md` §5.4._',
  ].join('\n');
  const res = await fetch(`https://api.github.com/repos/${repo}/issues`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ title, body, labels: ['flag-debt'] }),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub create-issue failed ${res.status}: ${text}`);
  }
  return (await res.json()) as { number: number };
}

export const flagDebtAudit = inngest.createFunction(
  {
    id: INNGEST_FUNCTION_IDS.FLAG_DEBT_AUDIT,
    triggers: [{ cron: '0 6 * * 1' }], // Mondays 06:00 UTC
  },
  async ({ step }) => {
    const logger = console;
    const overdue = await step.run('load-and-find-overdue', () => {
      const manifest = loadManifest();
      return findOverdue(manifest, new Date());
    });

    if (overdue.length === 0) {
      logger.info('flag_debt_audit: no overdue flags', {});
      return { opened: 0, alreadyOpen: 0, overdueCount: 0 };
    }

    const githubToken = process.env.GITHUB_TOKEN;
    const repo = process.env.GITHUB_REPO ?? 'Isk4R1oT/mcpgen';
    if (githubToken === undefined) {
      logger.warn('flag_debt_audit: GITHUB_TOKEN unset — skipping issue creation', {
        overdueCount: overdue.length,
      });
      return { opened: 0, alreadyOpen: 0, overdueCount: overdue.length };
    }

    let opened = 0;
    let alreadyOpen = 0;
    for (const flag of overdue) {
      const title = `flag-debt: ${flag.key} overdue by ${flag.daysOverdue} day(s)`;
      const existing = await step.run(`find-${flag.key}`, () =>
        findExistingIssue(repo, githubToken, title),
      );
      if (existing !== undefined) {
        alreadyOpen += 1;
        continue;
      }
      const created = await step.run(`create-${flag.key}`, () =>
        createIssue(repo, githubToken, flag),
      );
      logger.info('flag_debt_audit: opened issue', {
        flagKey: flag.key,
        issueNumber: created.number,
      });
      opened += 1;
    }

    return { opened, alreadyOpen, overdueCount: overdue.length };
  },
);
